### ISSUE TITLE
Please update readme

### ISSUE THREAD

**Issue by spyshiv** [MSG91/sendotp-python#1]
According to the current readme
I am getting this error while trying to send otp via this method.

`otpobj.send(91xxxxxxxxxx, 'msgind')`

**Error**
`TypeError: send() takes exactly 4 arguments (3 given)`
What are these 4 arguments please specify in readme. And also there should be an option to send countrycode as an argument.

**Comment by rwalkover** [comment]
Thanks for updating us. We will correct it soon.
